version: '3.3'

services:
  db:
    image: percona/percona-server:latest
    container_name: myken9_db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - ./schema/schema.sql:/schema.sql
      - mysqldata-myken9:/var/lib/mysql
  
volumes:
  mysqldata-myken9: