// Code generated by protoc-gen-go. DO NOT EDIT.
// source: library.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Search               string   `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8a1c5bd42931444, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type Book struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8a1c5bd42931444, []int{1}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Author struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8a1c5bd42931444, []int{2}
}

func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (m *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(m, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Author) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Books struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Books) Reset()         { *m = Books{} }
func (m *Books) String() string { return proto.CompactTextString(m) }
func (*Books) ProtoMessage()    {}
func (*Books) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8a1c5bd42931444, []int{3}
}

func (m *Books) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Books.Unmarshal(m, b)
}
func (m *Books) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Books.Marshal(b, m, deterministic)
}
func (m *Books) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Books.Merge(m, src)
}
func (m *Books) XXX_Size() int {
	return xxx_messageInfo_Books.Size(m)
}
func (m *Books) XXX_DiscardUnknown() {
	xxx_messageInfo_Books.DiscardUnknown(m)
}

var xxx_messageInfo_Books proto.InternalMessageInfo

func (m *Books) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type Authors struct {
	Authors              []*Author `protobuf:"bytes,1,rep,name=authors,proto3" json:"authors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Authors) Reset()         { *m = Authors{} }
func (m *Authors) String() string { return proto.CompactTextString(m) }
func (*Authors) ProtoMessage()    {}
func (*Authors) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8a1c5bd42931444, []int{4}
}

func (m *Authors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authors.Unmarshal(m, b)
}
func (m *Authors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authors.Marshal(b, m, deterministic)
}
func (m *Authors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authors.Merge(m, src)
}
func (m *Authors) XXX_Size() int {
	return xxx_messageInfo_Authors.Size(m)
}
func (m *Authors) XXX_DiscardUnknown() {
	xxx_messageInfo_Authors.DiscardUnknown(m)
}

var xxx_messageInfo_Authors proto.InternalMessageInfo

func (m *Authors) GetAuthors() []*Author {
	if m != nil {
		return m.Authors
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "api.Request")
	proto.RegisterType((*Book)(nil), "api.Book")
	proto.RegisterType((*Author)(nil), "api.Author")
	proto.RegisterType((*Books)(nil), "api.Books")
	proto.RegisterType((*Authors)(nil), "api.Authors")
}

func init() { proto.RegisterFile("library.proto", fileDescriptor_f8a1c5bd42931444) }

var fileDescriptor_f8a1c5bd42931444 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x3d, 0x4f, 0x85, 0x30,
	0x14, 0x86, 0xc3, 0x67, 0xc3, 0x01, 0x1d, 0xce, 0x60, 0x88, 0x8b, 0xd8, 0x84, 0x04, 0x8d, 0x21,
	0x06, 0x7f, 0x81, 0x0e, 0x4e, 0x4e, 0x5d, 0x9d, 0x8a, 0x34, 0xa1, 0x51, 0x29, 0xb6, 0x30, 0xf8,
	0xef, 0x6f, 0xda, 0xc2, 0xcd, 0xbd, 0xdb, 0xdd, 0xde, 0xf6, 0x7d, 0x72, 0x9e, 0x9c, 0x03, 0x57,
	0x3f, 0xb2, 0xd7, 0x5c, 0xff, 0xb7, 0xb3, 0x56, 0x8b, 0xc2, 0x88, 0xcf, 0x92, 0xde, 0x03, 0x61,
	0xe2, 0x6f, 0x15, 0x66, 0xc1, 0x1b, 0x48, 0x8d, 0xe0, 0xfa, 0x6b, 0x2c, 0x83, 0x2a, 0x68, 0x32,
	0xb6, 0xbd, 0xe8, 0x23, 0xc4, 0x6f, 0x4a, 0x7d, 0xe3, 0x35, 0x84, 0x72, 0x70, 0x5d, 0xc2, 0x42,
	0x39, 0x20, 0x42, 0x3c, 0xf1, 0x5f, 0x51, 0x86, 0x8e, 0x76, 0x99, 0x3e, 0x41, 0xfa, 0xba, 0x2e,
	0xa3, 0xd2, 0x17, 0xd1, 0x0d, 0x24, 0x76, 0xb2, 0xc1, 0x3b, 0x48, 0x7a, 0x1b, 0xca, 0xa0, 0x8a,
	0x9a, 0xbc, 0xcb, 0x5a, 0x3e, 0xcb, 0xd6, 0x56, 0xcc, 0xff, 0xd3, 0x67, 0x20, 0x7e, 0xae, 0xc1,
	0x1a, 0x08, 0xf7, 0x71, 0xa3, 0x73, 0x47, 0xfb, 0x9a, 0xed, 0x5d, 0xf7, 0x09, 0xe4, 0xc3, 0xaf,
	0x8b, 0x35, 0x64, 0xef, 0x72, 0x1a, 0xbc, 0xaa, 0x70, 0xf4, 0xb6, 0xf3, 0x2d, 0x1c, 0x4d, 0x06,
	0x1f, 0x20, 0xb7, 0xd8, 0xee, 0x39, 0x07, 0x8b, 0x13, 0x89, 0xe9, 0x53, 0x77, 0xc1, 0x97, 0x43,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xba, 0x98, 0x41, 0xda, 0x52, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LibraryClient is the client API for Library service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LibraryClient interface {
	FindBooks(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Books, error)
	FindAuthors(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Authors, error)
}

type libraryClient struct {
	cc *grpc.ClientConn
}

func NewLibraryClient(cc *grpc.ClientConn) LibraryClient {
	return &libraryClient{cc}
}

func (c *libraryClient) FindBooks(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Books, error) {
	out := new(Books)
	err := c.cc.Invoke(ctx, "/api.Library/FindBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) FindAuthors(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Authors, error) {
	out := new(Authors)
	err := c.cc.Invoke(ctx, "/api.Library/FindAuthors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LibraryServer is the server API for Library service.
type LibraryServer interface {
	FindBooks(context.Context, *Request) (*Books, error)
	FindAuthors(context.Context, *Request) (*Authors, error)
}

// UnimplementedLibraryServer can be embedded to have forward compatible implementations.
type UnimplementedLibraryServer struct {
}

func (*UnimplementedLibraryServer) FindBooks(ctx context.Context, req *Request) (*Books, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindBooks not implemented")
}
func (*UnimplementedLibraryServer) FindAuthors(ctx context.Context, req *Request) (*Authors, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAuthors not implemented")
}

func RegisterLibraryServer(s *grpc.Server, srv LibraryServer) {
	s.RegisterService(&_Library_serviceDesc, srv)
}

func _Library_FindBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).FindBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Library/FindBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).FindBooks(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_FindAuthors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).FindAuthors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Library/FindAuthors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).FindAuthors(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Library_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Library",
	HandlerType: (*LibraryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindBooks",
			Handler:    _Library_FindBooks_Handler,
		},
		{
			MethodName: "FindAuthors",
			Handler:    _Library_FindAuthors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "library.proto",
}
